spring:
  datasource:
    password: P@ssw0rd123
    url: jdbc:mysql://localhost:3306/newServerDB
    username: NewServerAdmin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
